### PR TITLE
Add numberless tiles

### PR DESCRIPTION
**Pull request by bradleysigma**
Adding a numberless version of each tile, with the name/number in the right corner of the tile being generatively filled. These tiles don't have any associated code (yet). Should mean that the tile location number can be directly printed on the tile without putting the banner mask on top, which looks slightly out of place. If desired, I could likely do a set with only the number removed, and the sector name remaining.

banner

### CODE REVIEW

**Comment by bradleysigma** [comment]
For comparison:

001 - Copy

**Comment by bradleysigma** [comment]
For the new tiles, I'm happy to repeat the process when they get added. You could temporarily embed the banner directly into the images for the numberless version of the tile until then (and I think it is useful to keep both the numbered and numberless versions of the tiles).

As for the contrast, adding a stroke to the numbers should make it readable regardless of the background. Below I took the brightest and darkest tiles in the region of the banner, and drew a number, and I think it's readable for both.

stroke

**Comment by bradleysigma** [comment]
On a related note, would it be worth creating a set of tiles with the wormholes removed with a generative fill, since they get masked off anyway?

**Comment by Fingon00** [comment]
Yes it would allow us to not use the wormhole cover, which looks slightly different than the background of most tiles

**Pull request merged**
