### PR TITLE
GamestateHelper added

### PR DESCRIPTION
**Pull request by TaylorBoyd**
Separated read and write to it's own class. No longer is this handled within the other helper classes.

Discovered a possible bug where coder would need to be VERY careful with how they ordered helper commands when read/write was inside. Now that it is separated it should be much easier to avoid accidental overwrites.

### CODE REVIEW

**Comment by sirraidsalot** [comment]
What's the motivation for having a separate Gamestatehelper and Playerhelper? Aren't the player stats part of the gamestate? Is something else going in the Playerhelper?

**Comment by TaylorBoyd** [comment]
I wanted the PlayerHelper class just to take in the player stats alone just to keep it clean...instead of the entire game state. And yes PlayerHelper will need to be build out with many more commands (drawing tiles, drawing techs, placing techs, building, taking turns, spending money, etc...). It's just keeping the different helpers separated so the code is fairly modular for each thing the class works on.

Originally I wrote it to take in the game state then both read and write to it within player helper. However, I had worries about needing to be VERY specific about the order of how you instantiated PlayerHelper classes in order to not overwrite the game state.

Take for example something like this:

p1 = PlayerHelper()
p2 = PlayerHelper()

p1.change_materials(10)
p2.change_materials(10)

I believe this would end up overwriting the changes made to p1, because p1 and p2 were instantiated with the original gamestate and it was not passed again into p2 with the changes p1 made after adjusting the materials. So I wanted to avoid needing to be careful about ordering things like this in the code and just do it only inside a Gamestate class.

**Comment by TaylorBoyd** [comment]
I guess we could put everything together in one single gamestate file, it's just going to have 1000's of lines of code to contain all of the commands. Maybe that's not something we care about?

**Comment by sirraidsalot** [comment]
The reason I bring it up is that the player state is just a subset of the game state. Any time you update the player state, you are updating the game state. So the PlayerHelper class is just a level of obfuscation. For example,

`gamestate = GamestateHelper(interaction.channel)
player1 = PlayerHelper(discord_player1.id, gamestate.get_player_stats(discord_player1.id))

await interaction.response.send_message(player1.adjust_materials(adjustment))
gamestate.update_player_stats(player1.player_id, player1.stats)`

is identical to

`gamestate = GamestateHelper(interaction.channel)
before = gamestate.get_player_stats(discord_player1.id)["materials"]
gamestate.get_player_stats(discord_player1.id)["materials"] += adjustment

await interaction.response.send_message(f"Adjusted materials from {before} to {before+adjustment}")
gamestate.update()`

Maybe there are more complex interactions where it is easier to have the player state as its own variable that we will find later, so we can leave it for now.

**Comment by sirraidsalot** [comment]
In any case it's a nice base to build on for player and game commands.

**Pull request merged**
